backbones_network: 'darknet53' 
weightfile: 'data/weights/darknet53_weights_pytorch.pth'
image_path: 'data/coco/images'
imdb_name: 'coco_2014_train+coco_2014_valminusminival'
imdbval_name: 'coco_2014_minival'

# general setting:
batch_size: 64
max_epochs: 60
num_workers: 0

save_interval: 5
save_path: save/
dir_logs: logs/
height: 416
width: 416
seed: 123

# optimization:
optimizer: 'adam'
backbone_lr: 0.000
lr: 0.001

weight_decay: 0
decay_gamma: 0.1
decay_step: 20
burn_in: 2000
steps: [-1, 1, 20, 25]
scales: [0.1, 10, 0.1, 0.1]

# loading options.
use_cuda: True
n_iter: 0
start_epoch: 0
start_from: ""
load_best_score: 0
display_interval: 20
seen: 0

anchors: [[10, 13], [16, 30], [33, 23],
          [30, 61], [62, 45], [59, 119],
          [116, 90], [156, 198], [373, 326]]

classes: 80
use_all_gt: False